### PR TITLE
Allow WebSocket proxying

### PR DESCRIPTION
**Pull request by SteveLTN**

### CODE REVIEW

**Comment by 5an1ty** [comment]
Not sure why this seems to work without proxy_http_version.

But if you look at the documentation of NGINX:
Sets the HTTP protocol version for proxying. By default, version 1.0 is used. Version 1.1 is recommended for use with keepalive connections and NTLM authentication.

A websocket connection is a keepalive connection right?

**Comment by SteveLTN** [comment]
@5an1ty Yep, I read the Nginx document. But @dancek claimed so. Let's wait for his response first.

**Comment by dancek** [comment]
This is the config I use. Works for me (for weechat). I thought that keepalive is a separate concept but I'm no expert on HTTP specifics.

https://github.com/dancek/docker-hthartk/blob/master/https-portal/nginx-conf/irc.hthar.tk.ssl.conf.erb

**Comment by dancek** [comment]
I read a bit of nginx documentation, and it looks like the `Connection` header is set by default to `close`.

**Comment by SteveLTN** [comment]
Hi, I updated the code according to @dancek 's suggestion.

This branch is available on DockerHub as `steveltn/https-portal:websocket`. To enable this, just add `WEBSOCKET=true` to environment.

Can you guys test it? Or tell me your setup of the websocket application so I can test it.

**Comment by dancek** [comment]
Yes, I tested it and it works nicely!

**Pull request merged**
