### PR TITLE
Upgrade acme-tiny to 4.0.3 + disable self-check

### LINKED ISSUE #116: Verification fails, even though I can curl the challenge
using barebones docker-compose.yml:

```https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'savory-software.com'
    # STAGE: 'production'
```

When the verification process starts, I can curl the challenge:

```
curl --verbose http://savory-software.com/.well-known/acme-challenge/U4Qq1lvrYD3KXJ7OmLsZMcKgVGDVB0LJiDRWXxmgVsM
*   Trying 192.241.192.242...
* TCP_NODELAY set
* Connected to savory-software.com (192.241.192.242) port 80 (#0)
> GET /.well-known/acme-challenge/U4Qq1lvrYD3KXJ7OmLsZMcKgVGDVB0LJiDRWXxmgVsM HTTP/1.1
> Host: savory-software.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 18 Jan 2018 21:05:02 GMT
< Content-Type: application/octet-stream
< Content-Length: 87
< Last-Modified: Thu, 18 Jan 2018 21:03:09 GMT
< Connection: keep-alive
< ETag: "5a610b8d-57"
< Accept-Ranges: bytes
< 
* Connection #0 to host savory-software.com left intact
U4Qq1lvrYD3KXJ7OmLsZMcKgVGDVB0LJiDRWXxmgVsM.SItonyzMNwx6ug921M-JxJdor9MAAVOzJhfBtBgVTJAphilipkoberink
```

However, the acme-tiny client still fails -- 

```
https-portal_1  | [fix-attrs.d] applying owners & permissions fixes...
https-portal_1  | [fix-attrs.d] 00-runscripts: applying... 
https-portal_1  | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1  | [fix-attrs.d] done.
https-portal_1  | [cont-init.d] executing container initialization scripts...
https-portal_1  | [cont-init.d] 00-welcome: executing... 
https-portal_1  | 
https-portal_1  | ========================================
https-portal_1  | HTTPS-PORTAL v1.2.1
https-portal_1  | ========================================
https-portal_1  | 
https-portal_1  | [cont-init.d] 00-welcome: exited 0.
https-portal_1  | [cont-init.d] 10-setup: executing... 
https-portal_1  | 2018/01/18 21:03:09 [notice] 133#133: signal process started
https-portal_1  | Signing certificates from https://acme-staging.api.letsencrypt.org ...
https-portal_1  | Parsing account key...
https-portal_1  | Parsing CSR...
https-portal_1  | Registering account...
https-portal_1  | Already registered!
https-portal_1  | Verifying savory-software.com...
https-portal_1  | ================================================================================
https-portal_1  | Failed to sign savory-software.com, is DNS set up properly?
https-portal_1  | ================================================================================
https-portal_1  | Failed to obtain certs for savory-software.com
https-portal_1  | 2018/01/18 21:03:39 [notice] 152#152: signal process started
https-portal_1  | [cont-init.d] 10-setup: exited 0.
https-portal_1  | [cont-init.d] 20-set-docker-gen-status: executing... 
https-portal_1  | [cont-init.d] 20-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
https-portal_1  | Starting crond ...
https-portal_1  | 73.109.106.248 - - [18/Jan/2018:21:04:50 +0000] "GET /.well-known/acme-challenge/U4Qq1lvrYD3KXJ7OmLsZMcKgVGDVB0LJiDRWXxmgVsM HTTP/1.1" 200 87 "-" "curl/7.54.0" "-"
https-portal_1  | Traceback (most recent call last):
https-portal_1  |   File "/bin/acme_tiny", line 198, in <module>
https-portal_1  |     main(sys.argv[1:])
https-portal_1  |   File "/bin/acme_tiny", line 194, in main
https-portal_1  |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1  |   File "/bin/acme_tiny", line 123, in get_crt
https-portal_1  |     wellknown_path, wellknown_url))
https-portal_1  | ValueError: Wrote file to /var/www/default/challenges/U4Qq1lvrYD3KXJ7OmLsZMcKgVGDVB0LJiDRWXxmgVsM, but couldn't download http://savory-software.com/.well-known/acme-challenge/U4Qq1lvrYD3KXJ7OmLsZMcKgVGDVB0LJiDRWXxmgVsM
```

Any ideas or suggestions for troubleshooting here would be appreciated.
Thanks for creating https-portal!

-Philip

### PR DESCRIPTION
**Pull request by jacqt**
Fixes #116.

Ran into an issue very similar to #116  and I was able to fix it by upgrading acme-tiny to 4.0.3 and adding the disable-check flag passed to the acme client.

### CODE REVIEW

**Comment by SteveLTN** [comment]
> NOTE: Since Let's Encrypt's ACME v2 release (acme-tiny 4.0.0+), the intermediate certificate is included in the issued certificate download, so you no longer have to independently download the intermediate certificate and concatenate it to your signed certificate. If you have an bash script using acme-tiny <4.0 (e.g. before 2018-03-17) with acme-tiny 4.0.0+, then you may be adding the intermediate certificate to your signed_chain.crt twice (not a big deal, it should still work fine, but just makes the certificate slightly larger than it needs to be). To fix, simply remove the bash code where you're downloading the intermediate and adding it to the acme-tiny certificate output.

Do you mind removing the chaining step as well? If you feel not familiar with the codebase and want me to do it, feel free. Just tell me, I can merge your PR and do it myself later.

**Comment by jacqt** [comment]
Sorry - not too familiar with the codebase so don't really know where to make that change. Also - thanks for maintaining this repo!

**Comment by SteveLTN** [comment]
I merged your PR, but have not made a new release yet. I'll spend some time to remove the chaining step.

**Comment by jacqt** [comment]
Thank you! Your work is greatly appreciated here :)

**Pull request merged**
