### PR TITLE
WIP: Fixed #248 Use nginx command for postrotate because invoke-rc.d doesn…

### LINKED ISSUE #248: log rotation doesn't work
Hello!

I found logrotate doesn't work correctly.

https://github.com/SteveLTN/https-portal/commit/ada778c0759a0536f5758f6dbf4a532fb007537b#diff-0d569d44c262f49774d8bfa6db5529395f2c897ffacc2f7063de1e42d287545cR18

logrotate uses invoke-rc.d to reload nginx but this container doesn't contain /etc/init.d/nginx.

This results nginx continues writing to old log file.

May I send a PR to fix this issue?

### PR DESCRIPTION
**Pull request by kedama222**
This PR fixes #248.

test environment:
```
version: '2'
  
services:
  https-portal:
    build:
      context: '.'
    environment:
      DOMAINS: 'https-portal -> http://nginx'
      STAGE: 'local'
      ERROR_LOG: 'default'
      ACCESS_LOG: 'default'

  nginx:
    image: 'nginx'

  curl:
    image: 'alpine'
    command:
      - 'sh'
      - '-c'
      - |-
        apk add curl
        while sleep 10; do
          curl https://https-portal/ \
            -o /dev/null \
            -fkSs
        done
```

### CODE REVIEW

**Comment by SteveLTN** [comment]
Thanks! I'll have a closer look later.

**Comment by kedama222** [comment]
It worked. But owner and permission are different from old log.

```
$ docker-compose exec https-portal ls -l /var/log/nginx
total 1076
-rw-r----- 1 nginx nginx 288990 Dec  7 12:41 access.log
-rw-r--r-- 1 root  root  787479 Dec  7 03:44 access.log-20201207
-rw-r----- 1 nginx nginx     61 Dec  7 03:45 error.log
-rw-r--r-- 1 root  root     549 Dec  6 03:37 error.log-20201207
-rw-r----- 1 nginx nginx      0 Dec  7 03:45 logrotate.log
-rw-r--r-- 1 root  root    1932 Dec  7 03:45 logrotate.log-20201207
```

**Review by SteveLTN — APPROVED** [review]

**Comment by SteveLTN** [comment]
Merged, thank you!

**Comment by SteveLTN** [comment]
1.15.1 is released.

**Pull request merged**
